name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' 

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Package Alfred workflow
        run: |
          make package-alfred

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
